image: docker:latest
variables:
  DOCKER_DRIVER: overlay
services:
- docker:dind
before_script:
- docker info
- docker pull easycryptpa/ec-artefact-box:yao-ccs17
yao:
  only:
  - master
  - ci
  script:
  - >-
    docker run -v $PWD:/home/ci/yao easycryptpa/ec-artefact-box:yao-ccs17
    sh -c 'cd yao && opam config exec -- make check'
