dist: trusty
language: ocaml
image: docker:latest
branches:
  only:
  - master
services:
- docker
before_install:
- docker pull easycryptpa/ec-artefact-box:yao-ccs17
script:
- >-
  docker run -v $PWD:/home/ci/yao easycryptpa/ec-artefact-box:yao-ccs17
  sh -c 'cd yao && opam config exec -- make check'
