dist: trusty
language: ocaml
image: docker:latest
services:
- docker
before_script:
- docker pull easycryptpa/ec-artefact-box:yao-ccs17
yao:
  only:
  - master
  script:
  - >-
    docker run -v $PWD:/home/ci/yao easycryptpa/ec-artefact-box:yao-ccs17
    sh -c 'cd yao && opam config exec -- make check'
